<template><section class="flex h-full min-h-0 flex-col bg-neutral-100 p-4 sm:p-6"><header><p class="text-sm font-medium text-neutral-500">{{ route.meta.group }}</p><h1 class="mt-1 text-2xl font-semibold text-neutral-900">{{ route.meta.title }}</h1><div class="mt-4 inline-flex rounded-md border border-neutral-200 bg-white p-1"><button class="rounded px-3 py-1.5 text-sm" :class="kind === 'text' ? 'bg-neutral-900 text-white' : 'text-neutral-600'" type="button" @click="kind = 'text'">文本</button><button class="rounded px-3 py-1.5 text-sm" :class="kind === 'file' ? 'bg-neutral-900 text-white' : 'text-neutral-600'" type="button" @click="kind = 'file'">文件</button></div></header><div class="mt-4 flex min-h-0 flex-1 flex-col gap-4"><div class="flex shrink-0 flex-wrap gap-2 rounded-lg border border-neutral-200 bg-white px-3 py-2"><button class="rounded-md bg-violet-600 px-3 py-1.5 text-sm text-white" type="button" @click="kind === 'text' ? input = 'TangTool Base64 示例' : selectFile()">示例/选择文件</button><button class="rounded-md bg-blue-600 px-3 py-1.5 text-sm text-white disabled:opacity-50" type="button" :disabled="kind === 'file' && path === ''" @click="kind === 'text' ? encode() : encodeFile()">Base64 编码</button><button class="rounded-md bg-cyan-600 px-3 py-1.5 text-sm text-white disabled:opacity-50" type="button" :disabled="kind === 'file' && path === ''" @click="kind === 'text' ? decode() : decodeFile()">Base64 解码</button><button class="rounded-md bg-emerald-600 px-3 py-1.5 text-sm text-white disabled:opacity-50" type="button" :disabled="result === ''" @click="copy">复制</button><button class="rounded-md bg-red-600 px-3 py-1.5 text-sm text-white" type="button" @click="clear">清除</button><p v-if="status" class="ml-auto text-sm text-emerald-700">{{ status }}</p></div><div class="grid min-h-0 flex-1 gap-4 lg:grid-cols-2"><section class="flex min-h-0 flex-col overflow-hidden rounded-lg border border-neutral-200 bg-white"><h2 class="border-b border-neutral-200 px-3 py-2 text-sm font-medium">{{ kind === 'text' ? '文本输入' : '文件输入' }}</h2><textarea v-if="kind === 'text'" v-model="input" class="min-h-0 flex-1 resize-none p-3 text-sm" aria-label="Base64 文本输入" placeholder="请输入文本" @input="reset"></textarea><button v-else class="m-4 rounded-lg border border-dashed border-neutral-300 bg-neutral-50 p-6 text-left text-sm" type="button" @click="selectFile">{{ fileName || '点击选择文件' }}</button></section><section class="flex min-h-0 flex-col overflow-hidden rounded-lg border border-neutral-200 bg-white"><h2 class="border-b border-neutral-200 px-3 py-2 text-sm font-medium">处理结果</h2><textarea class="min-h-0 flex-1 resize-none bg-neutral-50 p-3 font-mono text-sm" aria-label="Base64 结果" :value="result" readonly placeholder="结果显示在这里"></textarea><p class="border-t border-neutral-100 px-3 py-2 text-xs text-neutral-500">Base64 是编码方式，不是加密。</p><p v-if="error" class="border-t border-red-100 bg-red-50 px-3 py-2 text-sm text-red-700">{{ error }}</p></section></div></div></section></template>
<script setup lang="ts">
import { invoke } from "@tauri-apps/api/core"; import { open, save } from "@tauri-apps/plugin-dialog"; import { writeText } from "@tauri-apps/plugin-clipboard-manager"; import { ref } from "vue"; import { useRoute } from "vue-router";
const route = useRoute(); const kind = ref<'text'|'file'>('text'); const input = ref(''); const result = ref(''); const error = ref(''); const status = ref(''); const path = ref(''); const fileName = ref('');
function encode() { try { result.value = btoa(String.fromCharCode(...new TextEncoder().encode(input.value))); error.value = ''; status.value = '编码完成'; } catch { error.value = 'Base64 编码失败'; } }
function decode() { try { result.value = new TextDecoder().decode(Uint8Array.from(atob(input.value), (c) => c.charCodeAt(0))); error.value = ''; status.value = '解码完成'; } catch { result.value = ''; error.value = 'Base64 内容无效'; } }
async function selectFile() { const selected = await open({ title: '选择文件', multiple: false, directory: false }); if (typeof selected === 'string') { path.value = selected; fileName.value = selected.split(/[\\/]/).pop() || selected; status.value = '已选择文件'; } }
async function encodeFile() { const output = await save({ title: '保存 Base64 文件', defaultPath: `${fileName.value}.base64` }); if (!output || !path.value) return; try { await invoke('encode_file_base64', { path: path.value, outputPath: output }); status.value = 'Base64 文件已保存'; } catch (e) { error.value = typeof e === 'string' ? e : 'Base64 编码失败'; } }
async function decodeFile() { const output = await save({ title: '保存解码文件', defaultPath: `${fileName.value}.decoded` }); if (!output || !path.value) return; try { await invoke('decode_file_base64', { path: path.value, outputPath: output }); status.value = '文件解码完成'; } catch (e) { error.value = typeof e === 'string' ? e : 'Base64 解码失败'; } }
async function copy() { await writeText(result.value); status.value = '已复制到剪贴板'; } function reset() { result.value = ''; error.value = ''; status.value = ''; } function clear() { input.value = ''; result.value = ''; path.value = ''; fileName.value = ''; error.value = ''; status.value = ''; }
</script>
