<template><section class="flex h-full min-h-0 flex-col bg-neutral-100 p-4 sm:p-6"><header class="shrink-0"><p class="text-sm font-medium text-neutral-500">{{ route.meta.group }}</p><h1 class="mt-1 text-2xl font-semibold text-neutral-900">{{ route.meta.title }}</h1></header><div class="mt-4 flex min-h-0 flex-1 flex-col gap-4"><div class="flex shrink-0 flex-wrap items-center gap-2 rounded-lg border border-neutral-200 bg-white px-3 py-2"><button class="rounded-md bg-violet-600 px-3 py-1.5 text-sm font-medium text-white" type="button" @click="input = 'name=张三&keyword=照明灯具'">示例</button><button class="rounded-md bg-blue-600 px-3 py-1.5 text-sm font-medium text-white" type="button" @click="runEncode">URL 编码</button><button class="rounded-md bg-cyan-600 px-3 py-1.5 text-sm font-medium text-white" type="button" @click="runDecode">URL 解码</button><button class="rounded-md bg-emerald-600 px-3 py-1.5 text-sm font-medium text-white disabled:opacity-50" type="button" :disabled="result === ''" @click="copy">复制</button><button class="rounded-md bg-red-600 px-3 py-1.5 text-sm font-medium text-white" type="button" @click="clear">清除</button><p v-if="status" class="ml-auto text-sm text-emerald-700">{{ status }}</p></div><div class="grid min-h-0 flex-1 gap-4 lg:grid-cols-2"><textarea v-model="input" class="min-h-0 resize-none rounded-lg border border-neutral-200 bg-white p-3 font-mono text-sm" aria-label="URL 输入" placeholder="请输入 URL 或文本" @input="reset"></textarea><div class="flex min-h-0 flex-col rounded-lg border border-neutral-200 bg-white"><textarea class="min-h-0 flex-1 resize-none bg-neutral-50 p-3 font-mono text-sm" aria-label="URL 结果" :value="result" readonly placeholder="结果显示在这里"></textarea><p v-if="error" class="border-t border-red-100 bg-red-50 px-3 py-2 text-sm text-red-700">{{ error }}</p></div></div></div></section></template>
<script setup lang="ts">
import { writeText } from "@tauri-apps/plugin-clipboard-manager";
import { ref } from "vue";
import { useRoute } from "vue-router";
import { decodeUrlComponent, encodeUrlComponent } from "../utils/url";
const route = useRoute(); const input = ref(""); const result = ref(""); const error = ref(""); const status = ref("");
function run(value: ReturnType<typeof encodeUrlComponent>, message: string) { if (!value.ok) { result.value = ""; error.value = value.error; status.value = ""; return; } result.value = value.value; error.value = ""; status.value = message; }
function runEncode() { run(encodeUrlComponent(input.value), "编码完成"); } function runDecode() { run(decodeUrlComponent(input.value), "解码完成"); }
async function copy() { try { await writeText(result.value); status.value = "已复制到剪贴板"; } catch { error.value = "复制失败"; } } function reset() { result.value = ""; error.value = ""; status.value = ""; } function clear() { input.value = ""; reset(); }
</script>
